CREATE TABLE `users` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    account VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE directories (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT,
    path VARCHAR(255),
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
